# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_basic',
            name='user_id',
        ),
    ]
